### ISSUE TITLE
New ORM-lib ollie (the successor of ActiveAndroid)

### ISSUE THREAD

**Issue by Rainer-Lang** [ivangag/SyncAdapterActiveAndroid#1]
Do you plan also make this project with ollie?

**Comment by ivangag** [comment]
Sincerely i nicely have been using ActiveAndroid also for other my projects and don't plan to change that.
Also it seems that Ollie is not much documented for now (e.g. no wiki).
Nevertheless asap i'll have a look to other more recent ORM (e.g. DBFlow is interesting).

**Comment by Rainer-Lang** [comment]
Does DBFlow work with ContentProvider? 
Maybe this is an option for me.

**Comment by ivangag** [comment]
Good question.
I just submitted an issue https://github.com/Raizlabs/DBFlow/issues/44.
